- 
  apt_key: 
    state: present
    url: "https://download.docker.com/linux/ubuntu/gpg"
  name: "Add Docker GPG apt Key"

- 
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
  become: yes
  name: "Add Docker Repository"

-
  name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

-
  name: "Update apt and install docker-ce"
  apt: "name=docker-ce state=latest update_cache=yes"