- name: "Install kubectl"
  include_role:
    name: githubixx.kubectl

- name: "Install kubectl context plugin"
  become: yes
  unarchive:
    src: https://github.com/postfinance/kubectl-ctx/releases/download/v{{ kubectl.ctx.version }}/kubectl-ctx_linux_x86_64.zip
    dest: /usr/local/bin
    remote_src: yes
    include:
      - kubectl-ctx

- name: "Download k3sup installer"
  args:
    warn: false
  become: true
  shell: 
    cmd: "curl -sLS https://get.k3sup.dev | sh"
    chdir: "/tmp"
    creates: "/usr/local/bin/k3sup"

- name: "Install Helm"
  args:
    warn: false
  become: true
  shell: 
    cmd: "curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash"
    chdir: "/tmp"
    creates: "/usr/local/bin/helm"
