---
- name: "Install the nodejs LTS repos"
  apt_repository:
    repo: "deb https://deb.nodesource.com/setup_{{ nodejs }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- 
  args:
    warn: false
  become: true
  name: "Add nodejs deb"
  shell: "curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -"

- name: "Install the nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Add yarn app key"
  args:
    warn: false
  become: true
  shell: "curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"

- name: "Add yarn app repo"
  args:
    warn: false
  become: true
  shell: "echo \"deb https://dl.yarnpkg.com/debian/ stable main\" | sudo tee /etc/apt/sources.list.d/yarn.list"

- name: "Install yarn"
  apt:
    update_cache: yes
    name: yarn
    state: present