- name: "Remove nopref snapd to be able to install SNAPD"
  file:
    path: "/etc/apt/preferences.d/nosnap.pref"
    state: absent

-
  apt: "name=snapd state=latest update_cache=yes force_apt_get=yes"
  name: "Install snapd"

-
  name: "Install SNAP packages"
  shell: "snap install {{ item }}"
  loop: "{{ snap_packages }}"

-
  name: "Install SNAP packages"
  shell: "snap install {{ item }} --classic"
  loop: "{{ snap_packages_classic }}"
