- name: "Remove nopref snapd to be able to install SNAPD"
  file:
    path: "/etc/apt/preferences.d/nosnap.pref"
    state: absent

-
  apt: "name=snapd state=latest update_cache=yes force_apt_get=yes"
  name: "Install snapd"

-
  name: "Install SNAP packages"
  snap: 
    name: "{{ snap_packages }}"
- 
  name: "Install SNAP classic packages"
  snap:
    classic: true
    name: "{{ snap_packages_classic }}"