--- 
- 
  become: true
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
  pre_tasks:
    - import_tasks: ./tasks/prepare.yml
  tasks:
    - import_tasks: ./tasks/snap.yml
    - import_tasks: ./tasks/docker.yml
    - import_tasks: ./tasks/php.yml
    - import_tasks: ./tasks/k8s.yml
    - import_tasks: ./tasks/nodejs.yml
    - import_tasks: ./tasks/misc.yml